/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.FontArthurRodriguezCristian.vista;

import edu.ub.prog2.FontArthurRodriguezCristian.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author arthurfont
 */
public class AplicacioUB4 extends javax.swing.JFrame {
    private Controlador control;
    /**
     * Creates new form AplicacioUB4
     */
    public AplicacioUB4() {
        initComponents();
        control = new Controlador();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackGround = new javax.swing.JPanel();
        jPanelOptions = new javax.swing.JPanel();
        jButtonPlayFitxerBiblioteca = new javax.swing.JButton();
        btnEliminarAlbum = new javax.swing.JButton();
        btnCrearAlbum = new javax.swing.JButton();
        btnEliminarImatgeAlbum = new javax.swing.JButton();
        btnAfegirImatgeAlbum = new javax.swing.JButton();
        btnAfegirFitxerBiblioteca = new javax.swing.JButton();
        jButtonPlayFitxerAlbum = new javax.swing.JButton();
        btnEliminarImatge = new javax.swing.JButton();
        jButtonGuardarDades = new javax.swing.JButton();
        jButtonCargarDades = new javax.swing.JButton();
        jPanelReproduccio = new javax.swing.JPanel();
        jToggleButtonPlayPause = new javax.swing.JToggleButton();
        jButtonNext = new javax.swing.JButton();
        jButtonStop = new javax.swing.JButton();
        jPanelRandom = new javax.swing.JPanel();
        jButtonRandom = new javax.swing.JButton();
        jPanelContinue = new javax.swing.JPanel();
        jButtonContinue = new javax.swing.JButton();
        jPanelMusic = new javax.swing.JPanel();
        jPanelAlbum = new javax.swing.JPanel();
        jButtonPlayAlbum = new javax.swing.JButton();
        jComboBoxAlbums = new javax.swing.JComboBox<>();
        jScrollPaneAlbum = new javax.swing.JScrollPane();
        modelAlbum = new DefaultListModel();
        jListAlbum = new javax.swing.JList<>(modelAlbum);
        jPanelBiblioteca = new javax.swing.JPanel();
        jButtonPlayBiblioteca = new javax.swing.JButton();
        jScrollPaneBiblioteca = new javax.swing.JScrollPane();
        model = new DefaultListModel();
        jListBiblioteca = new javax.swing.JList<>(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AllianzMusic");
        setBackground(new java.awt.Color(1, 1, 1));
        setForeground(java.awt.Color.red);

        jPanelBackGround.setBackground(new java.awt.Color(58, 57, 56));

        jPanelOptions.setBackground(new java.awt.Color(29, 63, 122));

        jButtonPlayFitxerBiblioteca.setText("PlayFitxerBiblioteca");
        jButtonPlayFitxerBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayFitxerBibliotecaActionPerformed(evt);
            }
        });

        btnEliminarAlbum.setText("EliminarAlbum");
        btnEliminarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlbumActionPerformed(evt);
            }
        });

        btnCrearAlbum.setText("CrearAlbum");
        btnCrearAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearAlbumActionPerformed(evt);
            }
        });

        btnEliminarImatgeAlbum.setText("EliminarFitxerAlbum");
        btnEliminarImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImatgeAlbumActionPerformed(evt);
            }
        });

        btnAfegirImatgeAlbum.setText("AfegirFitxerAlbum");
        btnAfegirImatgeAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirImatgeAlbumActionPerformed(evt);
            }
        });

        btnAfegirFitxerBiblioteca.setText("AfegirFitxerBiblioteca");
        btnAfegirFitxerBiblioteca.setMaximumSize(new java.awt.Dimension(125, 29));
        btnAfegirFitxerBiblioteca.setMinimumSize(new java.awt.Dimension(125, 29));
        btnAfegirFitxerBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerBibliotecaActionPerformed(evt);
            }
        });

        jButtonPlayFitxerAlbum.setText("PlayFitxerAlbum");
        jButtonPlayFitxerAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayFitxerAlbumActionPerformed(evt);
            }
        });

        btnEliminarImatge.setText("EliminarFitxerBiblioteca");
        btnEliminarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarImatgeActionPerformed(evt);
            }
        });

        jButtonGuardarDades.setText("Guardar");
        jButtonGuardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDadesActionPerformed(evt);
            }
        });

        jButtonCargarDades.setText("Cargar");
        jButtonCargarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCargarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarDades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlayFitxerBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAfegirFitxerBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPlayFitxerAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarImatgeAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAfegirImatgeAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearAlbum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarImatge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAfegirFitxerBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAfegirImatgeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarImatgeAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPlayFitxerBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPlayFitxerAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGuardarDades, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCargarDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelReproduccio.setBackground(new java.awt.Color(28, 59, 113));
        jPanelReproduccio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 49, 75), 7));

        jToggleButtonPlayPause.setText("Pause");
        jToggleButtonPlayPause.setIconTextGap(0);
        jToggleButtonPlayPause.setPreferredSize(new java.awt.Dimension(115, 25));
        jToggleButtonPlayPause.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jToggleButtonPlayPauseItemStateChanged(evt);
            }
        });
        jToggleButtonPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPlayPauseActionPerformed(evt);
            }
        });

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonStop.setText("Atura");
        jButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopActionPerformed(evt);
            }
        });

        jPanelRandom.setBackground(new java.awt.Color(28, 59, 113));

        jButtonRandom.setText("Random");
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRandomLayout = new javax.swing.GroupLayout(jPanelRandom);
        jPanelRandom.setLayout(jPanelRandomLayout);
        jPanelRandomLayout.setHorizontalGroup(
            jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonRandom)
                .addGap(5, 5, 5))
        );
        jPanelRandomLayout.setVerticalGroup(
            jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonRandom)
                .addGap(5, 5, 5))
        );

        jPanelContinue.setBackground(new java.awt.Color(28, 59, 113));

        jButtonContinue.setText("Continue");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContinueLayout = new javax.swing.GroupLayout(jPanelContinue);
        jPanelContinue.setLayout(jPanelContinueLayout);
        jPanelContinueLayout.setHorizontalGroup(
            jPanelContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContinueLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonContinue)
                .addGap(5, 5, 5))
        );
        jPanelContinueLayout.setVerticalGroup(
            jPanelContinueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContinueLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButtonContinue)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanelReproduccioLayout = new javax.swing.GroupLayout(jPanelReproduccio);
        jPanelReproduccio.setLayout(jPanelReproduccioLayout);
        jPanelReproduccioLayout.setHorizontalGroup(
            jPanelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReproduccioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonStop)
                .addGap(15, 15, 15)
                .addComponent(jToggleButtonPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanelContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReproduccioLayout.setVerticalGroup(
            jPanelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReproduccioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelReproduccioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jToggleButtonPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStop)
                    .addComponent(jButtonNext)
                    .addComponent(jPanelRandom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMusic.setBackground(new java.awt.Color(30, 60, 120));
        jPanelMusic.setForeground(new java.awt.Color(245, 2, 2));

        jPanelAlbum.setBackground(new java.awt.Color(67, 67, 67));

        jButtonPlayAlbum.setText("Play");
        jButtonPlayAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayAlbumActionPerformed(evt);
            }
        });

        jComboBoxAlbums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlbumsActionPerformed(evt);
            }
        });

        jListAlbum.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jListAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAlbumMouseClicked(evt);
            }
        });
        jScrollPaneAlbum.setViewportView(jListAlbum);

        javax.swing.GroupLayout jPanelAlbumLayout = new javax.swing.GroupLayout(jPanelAlbum);
        jPanelAlbum.setLayout(jPanelAlbumLayout);
        jPanelAlbumLayout.setHorizontalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelAlbumLayout.createSequentialGroup()
                        .addComponent(jComboBoxAlbums, 0, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlayAlbum)))
                .addContainerGap())
        );
        jPanelAlbumLayout.setVerticalGroup(
            jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlbumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlayAlbum)
                    .addComponent(jComboBoxAlbums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneAlbum)
                .addContainerGap())
        );

        jPanelBiblioteca.setBackground(new java.awt.Color(68, 68, 68));

        jButtonPlayBiblioteca.setText("Play");
        jButtonPlayBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayBibliotecaActionPerformed(evt);
            }
        });

        jListBiblioteca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biblioteca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jListBiblioteca.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jListBibliotecaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPaneBiblioteca.setViewportView(jListBiblioteca);

        javax.swing.GroupLayout jPanelBibliotecaLayout = new javax.swing.GroupLayout(jPanelBiblioteca);
        jPanelBiblioteca.setLayout(jPanelBibliotecaLayout);
        jPanelBibliotecaLayout.setHorizontalGroup(
            jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBibliotecaLayout.createSequentialGroup()
                        .addGap(0, 140, Short.MAX_VALUE)
                        .addComponent(jButtonPlayBiblioteca)))
                .addContainerGap())
        );
        jPanelBibliotecaLayout.setVerticalGroup(
            jPanelBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBibliotecaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPlayBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneBiblioteca)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMusicLayout = new javax.swing.GroupLayout(jPanelMusic);
        jPanelMusic.setLayout(jPanelMusicLayout);
        jPanelMusicLayout.setHorizontalGroup(
            jPanelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMusicLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMusicLayout.setVerticalGroup(
            jPanelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMusicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMusicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAlbum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBackGroundLayout = new javax.swing.GroupLayout(jPanelBackGround);
        jPanelBackGround.setLayout(jPanelBackGroundLayout);
        jPanelBackGroundLayout.setHorizontalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                        .addComponent(jPanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jPanelMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelReproduccio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBackGroundLayout.setVerticalGroup(
            jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReproduccio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImatgeActionPerformed
        // TODO add your handling code here:
        int[] arrayIndex;
        arrayIndex = jListBiblioteca.getSelectedIndices();
        for (int i = arrayIndex.length-1; i >= 0; i--) {
            try {
                control.esborrarFitxer(arrayIndex[i]);
            } catch (AplicacioException except) {
                except.getMessage();
            }
            finally {
                if (model.getSize()-1 == control.getSize()){

                    while (modelAlbum.contains(model.getElementAt(arrayIndex[i]))) {
                        modelAlbum.removeElement(model.getElementAt(arrayIndex[i]));
                    }
                    model.remove(arrayIndex[i]);
                }
            }
        }
    }//GEN-LAST:event_btnEliminarImatgeActionPerformed

    private void jButtonPlayFitxerAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayFitxerAlbumActionPerformed
        // TODO add your handling code here:
        control.obrirFinestraReproductor();
        if (!this.modelAlbum.isEmpty()) {
            String nomFitxer = this.jListAlbum.getSelectedValue();
            int id = model.indexOf(nomFitxer);
            try {
                this.control.reproduirFitxer(id);
            } catch (AplicacioException execpt) {
                execpt.getMessage();
            }
        }
    }//GEN-LAST:event_jButtonPlayFitxerAlbumActionPerformed

    private void btnAfegirFitxerBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerBibliotecaActionPerformed
        // TODO add your handling code here:
        FrmAfegirFitxerMultimedia frame = new FrmAfegirFitxerMultimedia(this, rootPaneCheckingEnabled, control);
        frame.setVisible(true);
        while (frame.isVisible()){
            // espera
        }
        if (model.size() + 1 == control.getSize()){
            model.addElement(control.mostrarBiblioteca().get(control.getSize()-1));
        }
    }//GEN-LAST:event_btnAfegirFitxerBibliotecaActionPerformed

    private void btnAfegirImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirImatgeAlbumActionPerformed
        // TODO add your handling code here:
        int[] arrayIndex;
        arrayIndex = jListBiblioteca.getSelectedIndices();
        int i = this.jComboBoxAlbums.getSelectedIndex();
        String nomAlbum;
        if (i != -1){
            nomAlbum = jComboBoxAlbums.getSelectedItem().toString();
            for (int x = 0; x < arrayIndex.length; x++) {
                try {
                    control.afegirFitxer(nomAlbum, arrayIndex[x]);
                    modelAlbum.addElement(control.mostrarAlbum(nomAlbum).get(control.getSizeAlbum(nomAlbum)-1));
                } catch (AplicacioException except) {
                    except.getMessage();
                }
            }
        }
    }//GEN-LAST:event_btnAfegirImatgeAlbumActionPerformed

    private void btnEliminarImatgeAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImatgeAlbumActionPerformed
        // TODO add your handling code here:
        int[] arrayIndex;
        arrayIndex = jListAlbum.getSelectedIndices();
        int j = jComboBoxAlbums.getSelectedIndex();
        String nomAlbum;
        if (j != -1) {
            nomAlbum = jComboBoxAlbums.getSelectedItem().toString();
            for (int i = arrayIndex.length - 1; i >= 0; i--) {
                try {
                    control.esborrarFitxer(nomAlbum, arrayIndex[i]);
                } catch (AplicacioException except) {
                    except.getMessage();
                }
                finally {
                    try {
                        if (modelAlbum.getSize()-1 == control.getSizeAlbum(nomAlbum)){
                            modelAlbum.remove(arrayIndex[i]);
                        }
                    } catch (AplicacioException except) {
                        except.getMessage();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnEliminarImatgeAlbumActionPerformed

    private void btnCrearAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearAlbumActionPerformed
        // TODO add your handling code here:
        JOptionPane paneAlbum = new javax.swing.JOptionPane();
        String nomAlbum = "";
        nomAlbum = paneAlbum.showInputDialog(rootPane, "Nom de l'álbum:" ,"Crear àlbum", HEIGHT);
        try {
            control.afegirAlbum(nomAlbum);
            jComboBoxAlbums.addItem(nomAlbum);
        }
        catch (AplicacioException except) {
            except.getMessage();
        }
    }//GEN-LAST:event_btnCrearAlbumActionPerformed

    private void btnEliminarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlbumActionPerformed
        // TODO add your handling code here:
        if (jComboBoxAlbums.getSelectedIndex() != -1) {
            try {
                control.esborrarAlbum(jComboBoxAlbums.getSelectedItem().toString());
                jComboBoxAlbums.removeItem(jComboBoxAlbums.getSelectedItem());
            }
            catch (AplicacioException except) {
                except.getMessage();
            }
        }
    }//GEN-LAST:event_btnEliminarAlbumActionPerformed

    private void jButtonPlayFitxerBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayFitxerBibliotecaActionPerformed
        control.obrirFinestraReproductor();
        int id = this.jListBiblioteca.getSelectedIndex();
        try {
            this.control.reproduirFitxer(id);
        } catch (AplicacioException execpt) {
            execpt.getMessage();
        }
    }//GEN-LAST:event_jButtonPlayFitxerBibliotecaActionPerformed

    private void jButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopActionPerformed
        // TODO add your handling code here:
        try {
            this.control.tancarFinestraReproductor();
        } catch (AplicacioException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_jButtonStopActionPerformed

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        // TODO add your handling code here:
        this.control.setCiclica();
        if (control.isCiclic()) {
            this.jPanelContinue.setBackground(Color.green);
        }else {
            this.jPanelContinue.setBackground(Color.getColor("#1c3b71"));
        }
    }//GEN-LAST:event_jButtonContinueActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        try {
            this.control.saltaReproduccio();
        } catch (AplicacioException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        // TODO add your handling code here:
        this.control.setAleatori();
        if (control.isAleatori()) {
            this.jPanelRandom.setBackground(Color.green);
        }else {
            this.jPanelRandom.setBackground(Color.getColor("#1c3b71"));
        }
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jToggleButtonPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPlayPauseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonPlayPauseActionPerformed

    private void jToggleButtonPlayPauseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jToggleButtonPlayPauseItemStateChanged
        // TODO add your handling code here:
        if (jToggleButtonPlayPause.isSelected()) {
            try {
                this.control.pausaReproduccio();
                this.jToggleButtonPlayPause.setText("Play");
            } catch (AplicacioException ex) {
                ex.getMessage();
            }
        }else {
            try {
                this.control.reemprenReproduccio();
                this.jToggleButtonPlayPause.setText("Pause");
            } catch (AplicacioException ex) {
                ex.getMessage();
            }
        }
    }//GEN-LAST:event_jToggleButtonPlayPauseItemStateChanged

    private void jListBibliotecaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jListBibliotecaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jListBibliotecaAncestorAdded

    private void jButtonPlayBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayBibliotecaActionPerformed
        // TODO add your handling code here:
        control.obrirFinestraReproductor();
        if (!this.model.isEmpty()) {
            try {
                this.control.reproduirCarpeta();
            } catch (AplicacioException execpt) {
                execpt.getMessage();
            }
        }
    }//GEN-LAST:event_jButtonPlayBibliotecaActionPerformed

    private void jListAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAlbumMouseClicked

    }//GEN-LAST:event_jListAlbumMouseClicked

    private void jComboBoxAlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlbumsActionPerformed
        // TODO add your handling code here:
        int i = this.jComboBoxAlbums.getSelectedIndex();
        if (i != -1){
            jListAlbum.setBorder(javax.swing.BorderFactory.createTitledBorder(jComboBoxAlbums.getItemAt(i)));
            try {
                modelAlbum.removeAllElements();
                for (int j = 0; j < control.getSizeAlbum(this.jComboBoxAlbums.getSelectedItem().toString()); j++) {
                    try {
                        modelAlbum.addElement(control.mostrarAlbum(this.jComboBoxAlbums.getSelectedItem().toString()).get(j));
                    } catch (AplicacioException ex) {}
                }
            }catch (AplicacioException ex) {}
        }else {
            jListAlbum.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
            modelAlbum.removeAllElements();
        }
    }//GEN-LAST:event_jComboBoxAlbumsActionPerformed

    private void jButtonPlayAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayAlbumActionPerformed
        // TODO add your handling code here:
        control.obrirFinestraReproductor();
        if (this.jComboBoxAlbums.getSelectedIndex() != -1) {
            String nomAlbum = this.jComboBoxAlbums.getSelectedItem().toString();
            try {
                this.control.reproduirCarpeta(nomAlbum);
            } catch (AplicacioException execpt) {
                execpt.getMessage();
            }
        }
    }//GEN-LAST:event_jButtonPlayAlbumActionPerformed

    private void jButtonGuardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDadesActionPerformed
        // TODO add your handling code here:
        JOptionPane paneGuardarDades = new javax.swing.JOptionPane();
        String camiOrigen;
        camiOrigen = paneGuardarDades.showInputDialog(rootPane, "Camí on es guardarà el fitxer:" ,"Guardar dades", HEIGHT);
        if (camiOrigen.length() != 0) {
            try {
                control.guardarDadesDisc(camiOrigen);
            }
            catch (AplicacioException except) {
                except.getMessage();
            }
        }
    }//GEN-LAST:event_jButtonGuardarDadesActionPerformed

    private void jButtonCargarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDadesActionPerformed
        // TODO add your handling code here:
        JOptionPane paneGuardarDades = new javax.swing.JOptionPane();
        String camiDesti;
        camiDesti = paneGuardarDades.showInputDialog(rootPane, "Camí on es troba el fitxer:" ,"Carregar dades", HEIGHT);
        if (camiDesti.length() != 0) {
            try {
                control.carregarDadesDisc(camiDesti);
            }
            catch (AplicacioException except) {
                except.getMessage();
            }
        }
        model.removeAllElements();
        for (int j = 0; j < control.getSize(); j++) {
            model.addElement(control.mostrarBiblioteca().get(j));
        } // /home/arthurfont/Downloads/dades.dat
        jComboBoxAlbums.removeAllItems();
        for (int j = 0; j < control.getSizeListaAlbums(); j++) {
            jComboBoxAlbums.addItem(control.mostrarLlistatAlbums().get(j));
        }
    }//GEN-LAST:event_jButtonCargarDadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacioUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxerBiblioteca;
    private javax.swing.JButton btnAfegirImatgeAlbum;
    private javax.swing.JButton btnCrearAlbum;
    private javax.swing.JButton btnEliminarAlbum;
    private javax.swing.JButton btnEliminarImatge;
    private javax.swing.JButton btnEliminarImatgeAlbum;
    private javax.swing.JButton jButtonCargarDades;
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JButton jButtonGuardarDades;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPlayAlbum;
    private javax.swing.JButton jButtonPlayBiblioteca;
    private javax.swing.JButton jButtonPlayFitxerAlbum;
    private javax.swing.JButton jButtonPlayFitxerBiblioteca;
    private javax.swing.JButton jButtonRandom;
    private javax.swing.JButton jButtonStop;
    private javax.swing.JComboBox<String> jComboBoxAlbums;
    private javax.swing.JList<String> jListAlbum;
    private DefaultListModel<String> modelAlbum;
    private javax.swing.JList<String> jListBiblioteca;
    private DefaultListModel<String> model;
    private javax.swing.JPanel jPanelAlbum;
    private javax.swing.JPanel jPanelBackGround;
    private javax.swing.JPanel jPanelBiblioteca;
    private javax.swing.JPanel jPanelContinue;
    private javax.swing.JPanel jPanelMusic;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelRandom;
    private javax.swing.JPanel jPanelReproduccio;
    private javax.swing.JScrollPane jScrollPaneAlbum;
    private javax.swing.JScrollPane jScrollPaneBiblioteca;
    private javax.swing.JToggleButton jToggleButtonPlayPause;
    // End of variables declaration//GEN-END:variables
}