/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ub.prog2.FontArthurRodriguezCristian.vista;

import edu.ub.prog2.FontArthurRodriguezCristian.controlador.Controlador;
import edu.ub.prog2.utils.AplicacioException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author arthurfont
 */
public class FrmAfegirFitxerMultimedia extends javax.swing.JDialog {
    private static Controlador control;
    /**
     * Creates new form FrmAfegirFitxerMultimedia
     */
    public FrmAfegirFitxerMultimedia(java.awt.Frame parent, boolean modal, Controlador control) {
        super(parent, modal);
        initComponents();
        this.control = control;
        this.setPanelsFalse();
        this.jPanelAudio.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipi = new javax.swing.JPanel();
        jPanelVideo = new javax.swing.JPanel();
        textAlcada = new javax.swing.JTextField();
        textDuradaVideo = new javax.swing.JTextField();
        etDurada = new javax.swing.JLabel();
        textAmplada = new javax.swing.JTextField();
        textCodecVideo = new javax.swing.JTextField();
        etAmplada = new javax.swing.JLabel();
        etCodec = new javax.swing.JLabel();
        textFps = new javax.swing.JTextField();
        etNom = new javax.swing.JLabel();
        textNomVideo = new javax.swing.JTextField();
        etAlcada = new javax.swing.JLabel();
        etFps = new javax.swing.JLabel();
        jPanelAudio = new javax.swing.JPanel();
        textDuradaAudio = new javax.swing.JTextField();
        etDurada1 = new javax.swing.JLabel();
        textCodecAudio = new javax.swing.JTextField();
        etCodec1 = new javax.swing.JLabel();
        etNom1 = new javax.swing.JLabel();
        textNomAudio = new javax.swing.JTextField();
        textImatge = new javax.swing.JTextField();
        textKbps = new javax.swing.JTextField();
        etFps1 = new javax.swing.JLabel();
        etAlcada1 = new javax.swing.JLabel();
        jPanelAcceptar = new javax.swing.JPanel();
        btnAcceptar = new javax.swing.JButton();
        etCampsBuits = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jPanelPath = new javax.swing.JPanel();
        etCami = new javax.swing.JLabel();
        jButtonChooseFile = new javax.swing.JButton();
        comboOptionTipus = new javax.swing.JComboBox<>();
        etTipus = new javax.swing.JLabel();
        textCami = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 39));

        jPanelPrincipi.setBackground(new java.awt.Color(58, 57, 56));

        jPanelVideo.setBackground(new java.awt.Color(28, 59, 113));

        textAlcada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlcadaActionPerformed(evt);
            }
        });

        textDuradaVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuradaVideoActionPerformed(evt);
            }
        });

        etDurada.setForeground(new java.awt.Color(254, 254, 254));
        etDurada.setText("Durada:");

        textAmplada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAmpladaActionPerformed(evt);
            }
        });

        textCodecVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodecVideoActionPerformed(evt);
            }
        });

        etAmplada.setForeground(new java.awt.Color(254, 254, 254));
        etAmplada.setText("Amplada:");

        etCodec.setForeground(new java.awt.Color(254, 254, 254));
        etCodec.setText("Codec:");

        textFps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFpsActionPerformed(evt);
            }
        });

        etNom.setForeground(new java.awt.Color(254, 254, 254));
        etNom.setText("Nom:");

        textNomVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomVideoActionPerformed(evt);
            }
        });

        etAlcada.setBackground(new java.awt.Color(28, 59, 113));
        etAlcada.setForeground(new java.awt.Color(254, 254, 254));
        etAlcada.setText("Alçada:");

        etFps.setForeground(new java.awt.Color(254, 254, 254));
        etFps.setText("Fps:");

        javax.swing.GroupLayout jPanelVideoLayout = new javax.swing.GroupLayout(jPanelVideo);
        jPanelVideo.setLayout(jPanelVideoLayout);
        jPanelVideoLayout.setHorizontalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVideoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etNom)
                            .addComponent(etCodec)))
                    .addComponent(etDurada)
                    .addComponent(etAlcada)
                    .addComponent(etAmplada)
                    .addComponent(etFps))
                .addGap(18, 18, 18)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAlcada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textDuradaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCodecVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVideoLayout.setVerticalGroup(
            jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVideoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCodec, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCodecVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etDurada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDuradaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etAlcada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlcada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAmplada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFps, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAudio.setBackground(new java.awt.Color(28, 59, 113));

        textDuradaAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuradaAudioActionPerformed(evt);
            }
        });

        etDurada1.setForeground(new java.awt.Color(254, 254, 254));
        etDurada1.setText("Durada:");

        textCodecAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodecAudioActionPerformed(evt);
            }
        });

        etCodec1.setForeground(new java.awt.Color(254, 254, 254));
        etCodec1.setText("Codec:");

        etNom1.setForeground(new java.awt.Color(254, 254, 254));
        etNom1.setText("Nom:");

        textNomAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomAudioActionPerformed(evt);
            }
        });

        textImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textImatgeActionPerformed(evt);
            }
        });

        textKbps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKbpsActionPerformed(evt);
            }
        });

        etFps1.setForeground(new java.awt.Color(254, 254, 254));
        etFps1.setText("Kbps:");

        etAlcada1.setForeground(new java.awt.Color(254, 254, 254));
        etAlcada1.setText("Imatge:");

        javax.swing.GroupLayout jPanelAudioLayout = new javax.swing.GroupLayout(jPanelAudio);
        jPanelAudio.setLayout(jPanelAudioLayout);
        jPanelAudioLayout.setHorizontalGroup(
            jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etFps1)
                    .addComponent(etAlcada1)
                    .addGroup(jPanelAudioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etNom1)
                            .addComponent(etCodec1)))
                    .addComponent(etDurada1))
                .addGap(18, 18, 18)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(textImatge, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textKbps, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textDuradaAudio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textCodecAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNomAudio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAudioLayout.setVerticalGroup(
            jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAudioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCodec1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCodecAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etDurada1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDuradaAudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textImatge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etAlcada1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etFps1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKbps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        jPanelAcceptar.setBackground(new java.awt.Color(28, 59, 113));

        btnAcceptar.setText("Acceptar");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        etCampsBuits.setBackground(new java.awt.Color(150, 142, 135));
        etCampsBuits.setForeground(new java.awt.Color(255, 0, 0));
        etCampsBuits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etCampsBuits.setToolTipText("");
        etCampsBuits.setAlignmentY(0.0F);
        etCampsBuits.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        etCampsBuits.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                etCampsBuitsPropertyChange(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcceptarLayout = new javax.swing.GroupLayout(jPanelAcceptar);
        jPanelAcceptar.setLayout(jPanelAcceptarLayout);
        jPanelAcceptarLayout.setHorizontalGroup(
            jPanelAcceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceptarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanelAcceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etCampsBuits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAcceptarLayout.createSequentialGroup()
                        .addComponent(btnAcceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        jPanelAcceptarLayout.setVerticalGroup(
            jPanelAcceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etCampsBuits, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAcceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAcceptar))
                .addContainerGap())
        );

        jPanelPath.setBackground(new java.awt.Color(28, 59, 113));

        etCami.setForeground(new java.awt.Color(254, 254, 254));
        etCami.setText("Cami:");

        jButtonChooseFile.setText("Choose file");
        jButtonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFileActionPerformed(evt);
            }
        });

        comboOptionTipus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audio", "Video" }));
        comboOptionTipus.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                comboOptionTipusInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        comboOptionTipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboOptionTipusActionPerformed(evt);
            }
        });

        etTipus.setForeground(new java.awt.Color(254, 254, 254));
        etTipus.setText("Tipus:");

        textCami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCamiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPathLayout = new javax.swing.GroupLayout(jPanelPath);
        jPanelPath.setLayout(jPanelPathLayout);
        jPanelPathLayout.setHorizontalGroup(
            jPanelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPathLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etCami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCami, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonChooseFile)
                .addGap(40, 40, 40)
                .addComponent(etTipus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboOptionTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPathLayout.setVerticalGroup(
            jPanelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPathLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etCami, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChooseFile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etTipus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOptionTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipiLayout = new javax.swing.GroupLayout(jPanelPrincipi);
        jPanelPrincipi.setLayout(jPanelPrincipiLayout);
        jPanelPrincipiLayout.setHorizontalGroup(
            jPanelPrincipiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipiLayout.createSequentialGroup()
                .addComponent(jPanelVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipiLayout.setVerticalGroup(
            jPanelPrincipiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipiLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(jPanelPrincipiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAudio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jPanelAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelPrincipi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textKbpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKbpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKbpsActionPerformed

    private void textImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textImatgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textImatgeActionPerformed

    private void textNomAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomAudioActionPerformed

    private void textCodecAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodecAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodecAudioActionPerformed

    private void textDuradaAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuradaAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuradaAudioActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void etCampsBuitsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_etCampsBuitsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_etCampsBuitsPropertyChange

    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        // TODO add your handling code here
        if (this.comboOptionTipus.getSelectedItem().toString().equals("Video")) {
            if (this.textCami.getText().length() == 0 || this.textNomVideo.getText().length() == 0  || this.textCodecVideo.getText().length() == 0
                || this.textDuradaVideo.getText().length() == 0  ||  this.textAlcada.getText().length() == 0  || this.textAmplada.getText().length() == 0
                || this.textFps.getText().length() == 0 ) {
                etCampsBuits.setText("Omplir els camps buits");
            }
            else {
                try {
                    control.afegirVideo(this.textCami.getText() + "/" + this.textNomVideo.getText(),
                        this.textNomVideo.getText(), this.textCodecVideo.getText(),
                        Float.parseFloat(this.textDuradaVideo.getText()),
                        Integer.parseInt(this.textAlcada.getText()),
                        Integer.parseInt(this.textAmplada.getText()),
                        Float.parseFloat(this.textFps.getText()) );
                }
                catch (AplicacioException except) {
                    except.getMessage();
                }
                this.setVisible(false);
            }
        }
        else {
            if (this.textCami.getText().length() == 0 || this.textNomAudio.getText().length() == 0  || this.textCodecAudio.getText().length() == 0
                || this.textDuradaAudio.getText().length() == 0  ||  this.textImatge.getText().length() == 0  || this.textKbps.getText().length() == 0) {
                etCampsBuits.setText("*Omplir els camps buits");
            }
            else {
                try {
                    control.afegirAudio(this.textCami.getText() + "/" + this.textNomAudio.getText(),
                        this.textImatge.getText(),
                        this.textNomAudio.getText(),
                        this.textCodecAudio.getText(),
                        Float.parseFloat(this.textDuradaAudio.getText()),
                        Integer.parseInt(this.textKbps.getText()));
                }
                catch (AplicacioException except) {
                    except.getMessage();
                }
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnAcceptarActionPerformed

    private void textNomVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomVideoActionPerformed

    private void textFpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFpsActionPerformed

    private void textCodecVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodecVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodecVideoActionPerformed

    private void textAmpladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAmpladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAmpladaActionPerformed

    private void textDuradaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuradaVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuradaVideoActionPerformed

    private void textAlcadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlcadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlcadaActionPerformed

    private void textCamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCamiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCamiActionPerformed

    private void comboOptionTipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboOptionTipusActionPerformed
        // TODO add your handling code here:
        if (this.comboOptionTipus.getSelectedItem().toString().equals("Audio")) {
            this.jPanelVideo.setVisible(false);
            this.jPanelAudio.setVisible(true);
        }
        else {
            this.jPanelAudio.setVisible(false);
            this.jPanelVideo.setVisible(true);
        }
    }//GEN-LAST:event_comboOptionTipusActionPerformed

    private void comboOptionTipusInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_comboOptionTipusInputMethodTextChanged

    }//GEN-LAST:event_comboOptionTipusInputMethodTextChanged

    private void jButtonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtermp3mp4 = new FileNameExtensionFilter("MP3/MP4","mp3", "mp4");
        FileNameExtensionFilter filtermp3 = new FileNameExtensionFilter("MP3","mp3");
        FileNameExtensionFilter filtermp4 = new FileNameExtensionFilter("MP4","mp4");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(filtermp3mp4);
        chooser.addChoosableFileFilter(filtermp3);
        chooser.addChoosableFileFilter(filtermp4);

        int returnVal = chooser.showOpenDialog(null);
        if (chooser.getSelectedFile() != null) {
            textCami.setText(chooser.getSelectedFile().getAbsolutePath().split("/" + chooser.getSelectedFile().getName())[0]);
            if (chooser.getSelectedFile().getName().substring(chooser.getSelectedFile().getName().length()-3).equals("mp3")) {
                comboOptionTipus.setSelectedIndex(0);
                textNomAudio.setText(chooser.getSelectedFile().getName());
                textCodecAudio.setText("codec");
                textDuradaAudio.setText("10");
                textImatge.setText("img");
                textKbps.setText("10");
            }else {
                comboOptionTipus.setSelectedIndex(1);
                textNomVideo.setText(chooser.getSelectedFile().getName());
                textCodecVideo.setText("codec");
                textDuradaVideo.setText("10");
                textAlcada.setText("10");
                textAmplada.setText("10");
                textFps.setText("10");
            }
        }
    }//GEN-LAST:event_jButtonChooseFileActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAfegirFitxerMultimedia dialog = new FrmAfegirFitxerMultimedia(new javax.swing.JFrame(), true, control);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void setPanelsFalse() {
        this.jPanelAudio.setVisible(false);
        this.jPanelVideo.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboOptionTipus;
    private javax.swing.JLabel etAlcada;
    private javax.swing.JLabel etAlcada1;
    private javax.swing.JLabel etAmplada;
    private javax.swing.JLabel etCami;
    private javax.swing.JLabel etCampsBuits;
    private javax.swing.JLabel etCodec;
    private javax.swing.JLabel etCodec1;
    private javax.swing.JLabel etDurada;
    private javax.swing.JLabel etDurada1;
    private javax.swing.JLabel etFps;
    private javax.swing.JLabel etFps1;
    private javax.swing.JLabel etNom;
    private javax.swing.JLabel etNom1;
    private javax.swing.JLabel etTipus;
    private javax.swing.JButton jButtonChooseFile;
    private javax.swing.JPanel jPanelAcceptar;
    private javax.swing.JPanel jPanelAudio;
    private javax.swing.JPanel jPanelPath;
    private javax.swing.JPanel jPanelPrincipi;
    private javax.swing.JPanel jPanelVideo;
    private javax.swing.JTextField textAlcada;
    private javax.swing.JTextField textAmplada;
    private javax.swing.JTextField textCami;
    private javax.swing.JTextField textCodecAudio;
    private javax.swing.JTextField textCodecVideo;
    private javax.swing.JTextField textDuradaAudio;
    private javax.swing.JTextField textDuradaVideo;
    private javax.swing.JTextField textFps;
    private javax.swing.JTextField textImatge;
    private javax.swing.JTextField textKbps;
    private javax.swing.JTextField textNomAudio;
    private javax.swing.JTextField textNomVideo;
    // End of variables declaration//GEN-END:variables
}
